apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-deployment
  labels:
    env: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      env: sandbox
  template:
    metadata:
      labels:
        env: sandbox
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: my-volume-nginx
            mountPath: /app
      volumes:
        - name: my-volume-nginx
          persistentVolumeClaim:
            claimName: my-pvc

