apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment
  labels:
    env: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      env: sandbox
  template:
    metadata:
      labels:
        env: sandbox
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        env:
          - name: env-secret
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: password
